---
title: "Code Along - Data Viz"
output: html_document
date: "2023-10-12"
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path("figures/immerse_hex.png")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;',
               width ="250",
               height ="193")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE,
                      tidy.opts=list(width.cutoff=60)) #Here, I have made it so that when you knit your .rmd, warnings and messages will not show up in the html markdown. 
```

Load packages

```{r, cache = FALSE}

library(tidyverse)
library(haven)
library(glue)
library(MplusAutomation)
library(here)
library(janitor)
library(gt)
library(cowplot)
library(DiagrammeR) 
library(psych)
here::i_am("lca_viz.Rmd")
```


------------------------------------------------------------------------

## Day 1: Data Visualization

- Descriptive Statistics
- Table of Fit
- Information Criteria
- Probability Plots
- Classification Diagnostics

------------------------------------------------------------------------

Prepare Data

```{r, eval=TRUE}
df_bully <- read_csv(here("data", "crdc_lca_data.csv")) %>% 
  clean_names() %>% 
  dplyr::select(report_dis, report_race, report_sex, counselors_fte, psych_fte, law_fte) 
```


------------------------------------------------------------------------

### Descriptive Statistics

```{r}

```

------------------------------------------------------------------------

### Table of Fit

First, extract data:

```{r}

```

Then, create table:

```{r}

```


------------------------------------------------------------------------

### Information Criteria

```{r}

```

------------------------------------------------------------------------

### Probability Plots

Read in select model:

```{r}
model <- readModels(here("enum", "c3_bully.out"))
```


Automatic:


```{r fig.height=6, fig.width=10}
source("plot_lca.txt")

plot_lca(model_name = model)
```

------------------------------------------------------------------------

##### Customize Line Plot

Title: Bullying Probability Plot
Class Labels:
  1. Reported Harrassment (Low), Staff (High)
  2. Reported Harrassment (High), Staff (Low)
  3. Reported Harrassment (Low), Staff (Low)
Item Labels:
  1. Harassment: Disability
  2. Harassment: Race
  3. Harassment: Sex
  4. School staff: Counselor
  5. School staff: Psychologist
  6  School staff: Law Enforcement


```{r}
#### START EDIT ####

# Read in model
model <- 

# Title
title <- ""

# Item labels
items <- c("")

# Class labels
labels <- c("")


#### END EDIT ####

# Extract data needed for plotting (don't edit here)
plot_data <- data.frame(model$parameters$probability.scale) %>% 
  filter(category == 2) %>% 
  mutate(variable = fct_inorder(param),
         class = fct_inorder(LatentClass)) %>% 
  mutate(variable = factor(variable, labels = items),
         class = factor(class, labels = labels)) %>% 
  dplyr::select(est, se, class, variable)

```

#### Customize Line Plot

```{r}
## Plot data
plot_data %>%
  ggplot(
    aes(
      x = variable,
      y = est,
      shape = class,
      colour = class,
      lty = class,
      group = class
    )
  ) +
  geom_point(size = 4) + geom_line() +
  ylim(0,1) +
  scale_x_discrete("", labels = function(x) str_wrap(x, width = 10)) +
  labs(title = title, y = "Probability") +
  theme_cowplot() +
  # scale_color_manual(values=c('orange', 'pink', 'red')) +
  # scale_color_grey(end=.5) +
  # scale_shape_manual(values = c(7, 8, 9)) +
  theme(
    text = element_text(family = "serif", size = 12),
    legend.text = element_text(family = "serif", size = 12),
    legend.key.width = unit(0, "line"),
    legend.title = element_blank(),
    legend.position = "top",    
    axis.text.x = element_text(vjust = 1)
  )

```

Bar Plot:

```{r}
## Plot data
plot_data %>%
  ggplot(
    aes(
      x = variable,
      y = est,
      fill = class
    )
  ) +
  geom_bar(stat = "identity", position = "dodge", color = 'black') +
    geom_errorbar(aes(ymin=est-se, ymax=est+se),
                size=.3,    
                width=.2,
                position=position_dodge(.9)) +
  geom_text(aes(label = est), 
            family = "serif", size = 4,
            position=position_dodge(.9),
            vjust = -3) + # Change for location of text
  ylim(0,1) +
  scale_x_discrete("", labels = function(x) str_wrap(x, width = 10)) + # Adds string wrap to item names
  labs(title = title, y = "Probability") +
  theme_cowplot() +
  theme(
    text = element_text(family = "serif", size = 12),
    legend.text = element_text(family = "serif", size = 12),
    #legend.key.width = unit(0, "line"),
    legend.title = element_blank(),
    legend.position = "top",    
    axis.text.x = element_text(vjust = 1)
  ) 
```


------------------------------------------------------------------------

### Classification Diagnostics

```{r}

```













